package org.llvm.binding;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("LLVM") 
public class LLVMMCJITCompilerOptions extends StructObject {
	public LLVMMCJITCompilerOptions() {
		super();
	}
	@Field(0) 
	public int OptLevel() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public LLVMMCJITCompilerOptions OptLevel(int OptLevel) {
		this.io.setIntField(this, 0, OptLevel);
		return this;
	}
	/// C type : LLVMBool
	@Field(2) 
	public int NoFramePointerElim() {
		return this.io.getIntField(this, 2);
	}
	/// C type : LLVMBool
	@Field(2) 
	public LLVMMCJITCompilerOptions NoFramePointerElim(int NoFramePointerElim) {
		this.io.setIntField(this, 2, NoFramePointerElim);
		return this;
	}
	/// C type : LLVMBool
	@Field(3) 
	public int EnableFastISel() {
		return this.io.getIntField(this, 3);
	}
	/// C type : LLVMBool
	@Field(3) 
	public LLVMMCJITCompilerOptions EnableFastISel(int EnableFastISel) {
		this.io.setIntField(this, 3, EnableFastISel);
		return this;
	}
	public LLVMMCJITCompilerOptions(Pointer pointer) {
		super(pointer);
	}
}
