package org.llvm.binding;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("LLVM") 
public class LLVMOpInfo1 extends StructObject {
	public LLVMOpInfo1() {
		super();
	}
	/// C type : LLVMOpInfoSymbol1
	@Field(0) 
	public LLVMOpInfoSymbol1 AddSymbol() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : LLVMOpInfoSymbol1
	@Field(0) 
	public LLVMOpInfo1 AddSymbol(LLVMOpInfoSymbol1 AddSymbol) {
		this.io.setNativeObjectField(this, 0, AddSymbol);
		return this;
	}
	/// C type : LLVMOpInfoSymbol1
	@Field(1) 
	public LLVMOpInfoSymbol1 SubtractSymbol() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : LLVMOpInfoSymbol1
	@Field(1) 
	public LLVMOpInfo1 SubtractSymbol(LLVMOpInfoSymbol1 SubtractSymbol) {
		this.io.setNativeObjectField(this, 1, SubtractSymbol);
		return this;
	}
	@Field(2) 
	public long Value() {
		return this.io.getLongField(this, 2);
	}
	@Field(2) 
	public LLVMOpInfo1 Value(long Value) {
		this.io.setLongField(this, 2, Value);
		return this;
	}
	@Field(3) 
	public long VariantKind() {
		return this.io.getLongField(this, 3);
	}
	@Field(3) 
	public LLVMOpInfo1 VariantKind(long VariantKind) {
		this.io.setLongField(this, 3, VariantKind);
		return this;
	}
	public LLVMOpInfo1(Pointer pointer) {
		super(pointer);
	}
}
